# -*- coding: utf-8 -*-
"""Aplicación de minimizacion gran M 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yoo7LS5PcEQht7tYvRzziSBfc4_YEPW
"""

from scipy.optimize import linprog

M = 999999
c = [4, 2, 0, 0, 0, M, M]
A = [[5, 15, -1, 0, 0, 1, 0], [20, 5, 0, -1, 0, 0, 1], [15, 2, 0, 0, -1, 0, 0]]
b = [50, 40, 60]
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
x3_bounds = (0, None)
x4_bounds = (0, None)
x5_bounds = (0,None)
x6_bounds = (0,None)



res = linprog(c=c,
              A_ub=A,
              b_ub=b,
              bounds=[x0_bounds,
                      x1_bounds,
                      x2_bounds,
                      x3_bounds,
                      x4_bounds,
                      x5_bounds,
                      x6_bounds],
              method='highs')

print(f'Optimal value: {res.fun+10.9}')
print(f'X1 value: {res.x+1}')
print(f'X2 value: {res.x+1}')
print(f' {res}')